### ISSUE TITLE
Create mentor hint branch?

### ISSUE THREAD

**Issue by rachaelcodes** [foundersandcoders/npm-introduction#2]
It might be useful to add notes for mentors. Here's some questions I asked the group to check they'd followed everything:

1) what is npm? what does it do?
2) what's the difference between npm init and npm install? which would you run first?
3) what is a .gitignore? why might we use it?
4) what flag saves a module globally? what might the disadvantages of doing this be?
5) what is the difference between --save and --save-dev?

**Comment by rachaelcodes** [comment]
the branch could also include a link to these introductory slides: https://slides.com/rachaelcodes/deck/live#/

**Comment by zurda** [comment]
@rachaelcodes, thanks for the suggestion. We looked into this issue while preparing the material for FAC-16. Personally speaking, I felt this introductory is fairly short and includes all the answers to the above questions so I didn't feel an additional hint branch is needed. 
Having sais that, it is possible this intro was edited since the issue was opened, or perhaps I'm missing something, so I'm also cc'ing the maintainers: @astroash @eliascodes

**Comment by oliverjam** [comment]
I think Rachael was suggesting this as a guide for mentors to check the cohort understands everything they just read. Maybe see how next week goes and close this if you don't feel like it's necessary

**Comment by zurda** [comment]
Oh, sorry for misunderstanding @oliverjam . Yes, definitely, asking these questions would be really helpful just in case anything wasn't understood. We'll try that tomorrow (cc @aterna01 )

**Comment by rachaelcodes** [comment]
Yes, thanks for clarifying @oliverjam  - I was suggesting it would be something to help mentors. Hope the mentoring is going well @zurda 😄

**Comment by zurda** [comment]
Yes, @rachaelcodes, mentoring was an amazing experience, thanks for asking :) 

With regards to this issue: assessing understanding through these questions would have been nice but wasn't easy because of time constraints. The first hour of this week was a bit busy since it has (1) learning outcomes, (2) intro to npm, (3) intro to testing all in the first hour. 

Now that the week is over I agree with you - asking them directly would have been great, and adding it to the notes can improve how the morning went. I'm happy to create a PR
